project_id = "yufsreqnhwjodgdpbrjm"

[functions.reflection-chat]
verify_jwt = false

[functions.dashboard-analysis]
verify_jwt = false

[functions.mentor-letter]
verify_jwt = false

[functions.receive-chat-protocol]
verify_jwt = false

[functions.gap-analysis]
verify_jwt = false
